### ISSUE TITLE
unable to search

### ISSUE THREAD

**Issue by adahinden** [camptocamp/cgxp#1003]
After following specific sequence of events it's not possible to search anymore:

* click in the search field (the emptyText disappears)
* do not enter any text (after clicking in the search field the user realize that he don't know a search name, so he would search in the map...)
* click or pan in the map (the emptyText of the search field appears in front of the cursor)
* then click in the search field again and enter some text
* the text will recognize as "emptyText" and not as search text

Workaround: click in the header or do a page reload

**Comment by ochriste** [comment]
maybe this was fixed with the following commit:
https://github.com/camptocamp/cgxp/commit/a8d0dbbc9a2f186ac994d166b0b0c338015b81ca
to verify

**Comment by adahinden** [comment]
I did just a test on https://geomapfish-demo.camptocamp.net/1.6 and find that now it's better, but not completely solved.

* Better: the user is now able to search with "emptyText" text format
* Still not ok: after click in the search field again, the emptyText is still there (so the user must delete this text first)
